# Generated by Django 3.0.3 on 2020-03-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='mail',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
